=== seanean/shipment-events/schemas/shipment_products.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/werealldudes/statuses/schemas/status.json",
    "title": "Shipment Products Event",
    "description": "Describing the products shipment event.",
    "type": "object",
    "properties": {
        "event_name": {
            "description": "The name of the event.",
            "type": "string"
        },
        "event_timestamp": {
            "description": "The timestamp of the event.",
            "type": "string",
            "format": "date-time"
        },
        "event_id": {
            "description": "The ID of the event.",
            "type": "string"
        },
        "event_data": {
            "description": "The data of the event.",
            "type": "object",
            "properties": {
                "shipment_id": {
                    "description": "The ID of the shipment.",
                    "type": "string"
                },
                "shipment_business_id": {
                    "description": "The business ID of the shipment.",
                    "type": "string"
                }, 
                "shipment_type": {
                    "description": "The type of the shipment.",
                    "type": "string",
                    "enum": [
                        "ecommerce",
                        "wholesale",
                        "return"
                    ]
                }, 
                "products": {
                    "description": "The products of the shipment.",
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "product_id": {
                                "description": "The ID of the product.",
                                "type": "string"
                            },
                            "product_quantity": {
                                "description": "The quantity of the product.",
                                "type": "number"
                            }
                        },
                        "required": [
                            "product_id",
                            "product_quantity"
                        ]
                    }
                }
            },
            "required": [
                "shipment_id",
                "shipment_business_id",
                "shipment_type",
                "products"
            ]
        }
    },
    "required": [
        "event_name",
        "event_timestamp",
        "event_id",
        "event_data"
    ]
}

=== seanean/shipment-events/landing-zone/to-incrementally-move-in/shipment_products/dt=2026-04-05/products_example_e6_sh2.json
{
    "event_name": "shipmentProductsAllocated",
    "event_timestamp": "2026-04-04T11:00:00Z",
    "event_id": "e5",
    "event_data": {
        "shipment_id": "s1",
        "shipment_business_id": "sh_2",
        "shipment_type": "ecommerce",
        "products": [
            {
                "product_id": "p6",
                "product_quantity": 6
            },
            {
                "product_id": "p7",
                "product_quantity": 4
            }
        ]
    }
}

=== seanean/shipment-events/landing-zone/shipment_products/dt=2026-04-04/30b17bef-95e9-56e5-8927-72cea6a9ea38.json
{
    "event_name": "shipmentProductsAllocated",
    "event_timestamp": "2026-04-04T12:30:00Z",
    "event_id": "e2",
    "event_data": {
        "shipment_id": "s2",
        "shipment_business_id": "sh_2",
        "shipment_type": "wholesale",
        "products": [
            {
                "product_id": "p3",
                "product_quantity": 8
            },
            {
                "product_id": "p4",
                "product_quantity": 12
            }
        ]
    }
}
